export declare const enum TempCardIds {
	EclecticShrine = 'EclecticShrine',
	LokholarFrostforgeer = 'LokholarFrostforgeer',
	LokholarFrostforgeer_G = 'LokholarFrostforgeer_G',
	FountainPen = 'FountainPen',
	FountainPen_G = 'FountainPen_G',
	DrakkariPortrait = 'DrakkariPortrait',
	StharaSticker = 'StharaSticker',
	FelementalPortrait = 'FelementalPortrait',
	ImpulsiveTricksterPortrait = 'ImpulsiveTricksterPortrait',
	AshenCorruptor = 'AshenCorruptor',
	AshenCorruptor_G = 'AshenCorruptor_G',
	Shadowdancer = 'Shadowdancer',
	Shadowdancer_G = 'Shadowdancer_G',
	StaffOfEnrichment = 'StaffOfEnrichment',
}
