export declare const enum TempCardIds {
	HardyOrca = 'Temp_HardyOrca',
	HardyOrca_G = 'Temp_HardyOrca_G',
	HuntingTigerShark = 'Temp_HuntingTigerShark',
	HuntingTigerShark_G = 'Temp_HuntingTigerShark_G',
	StalwartKodo = 'Temp_StalwartKodo',
	StalwartKodo_G = 'Temp_StalwartKodo_G',
	Stuntdrake = 'Temp_Stuntdrake',
	Stuntdrake_G = 'Temp_Stuntdrake_G',
	TwilightBroodmother = 'Temp_TwilightBroodmother',
	TwilightBroodmother_G = 'Temp_TwilightBroodmother_G',
	TwilightHatchling = 'Temp_TwilightHatchling',
	TwilightHatchling_G = 'Temp_TwilightHatchling_G',
	WhelpWatcher = 'Temp_WhelpWatcher',
	WhelpWatcher_G = 'Temp_WhelpWatcher_G',
	TwilightWhelp = 'Temp_TwilightWhelp',
	TwilightWhelp_G = 'Temp_TwilightWhelp_G',
}
